[vms]
vm1 ansible_host=172.16.226.5 ansible_ssh_pass=yourPassword ansible_ssh_user=yourUser
vm2 ansible_host=172.16.226.56 ansible_ssh_pass=yourPassword ansible_ssh_user=yourUser
vm3 ansible_host=172.16.226.86 ansible_ssh_pass=yourPassword ansible_ssh_user=yourUser

# [vms:vars]
# ansible_python_interpreter=/usr/bin/python2.7 # needed for docker swarm

[manager]
# vm2
vm3

[worker]
vm1
vm2